### PR TITLE
Feature fetch Universal Profile names/pictures

### PR DESCRIPTION
**Pull request by Hugoo**

### CODE REVIEW

**Comment by mxmar** [comment]
@Wolmin :warning:  This merge should be against https://github.com/lukso-network/network-explorer-execution-frontend/tree/lukso - `main` branch is for upstream - fork strategy is explained there: https://www.notion.so/lukso/explorer-execution-fdb40ec6842f474abf0fa899d3452f67?pvs=4#c03bff8d844042e5942156320e2ddfbf

**Comment by mxmar** [comment]
> @Wolmin ⚠️ This merge should be against https://github.com/lukso-network/network-explorer-execution-frontend/tree/lukso - `main` branch is for upstream - fork strategy is explained there: https://www.notion.so/lukso/explorer-execution-fdb40ec6842f474abf0fa899d3452f67?pvs=4#c03bff8d844042e5942156320e2ddfbf

I've updated `main` with upstream commits, merged to `lukso` branch (there is strong LUKSO customization - footer, links etc), and I've changed target branch to `lukso` in this PR @Wolmin @richtera

**Review by Hugoo — COMMENTED** [review]
The PR looks good, i tihnk it will be very hard to make it work with remote source repo but... nvm.

It does the job so thats what matters.

**Comment by Wolmin** [comment]
image
image
image
image

Screenshots from transaction and search parts of the page

**Pull request merged**
